### ISSUE TITLE
Running gulp fails

### ISSUE THREAD

**Issue by DamienCassou** [foretagsplatsen/klassified#39]
```
gulp test
[09:43:28] Using gulpfile ~/Documents/projects/ftgp/klassified/gulpfile.js
[09:43:28] Starting 'test'...
10 02 2017 09:43:28.326:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
10 02 2017 09:43:28.335:INFO [launcher]: Starting browser PhantomJS
10 02 2017 09:44:28.397:WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
10 02 2017 09:44:30.403:WARN [launcher]: PhantomJS was not killed in 2000 ms, sending SIGKILL.
10 02 2017 09:44:32.404:WARN [launcher]: PhantomJS was not killed by SIGKILL in 2000 ms, continuing.
[09:44:32] 'test' errored after 1.07 min
[09:44:32] Error: 1
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/home/cassou/Documents/projects/ftgp/klassified/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/cassou/Documents/projects/ftgp/klassified/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/cassou/Documents/projects/ftgp/klassified/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/cassou/Documents/projects/ftgp/klassified/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/cassou/Documents/projects/ftgp/klassified/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/home/cassou/Documents/projects/ftgp/klassified/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1555:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Compilation exited abnormally with code 1 at Fri Feb 10 09:44:32
```

**Comment by BenjaminVanRyseghem** [comment]
if that was the case, the build server would flag red all PRs.

I think it's more a problem of yours, or?

**Comment by BenjaminVanRyseghem** [comment]
```
$> gulp test           
[11:16:45] Using gulpfile ~/FTGP/objectjs/gulpfile.js
[11:16:45] Starting 'test'...
10 02 2017 11:16:45.568:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
10 02 2017 11:16:45.575:INFO [launcher]: Starting browser PhantomJS
10 02 2017 11:16:46.430:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket 418Ro4st_e010RoNAAAA with id 56373387
............................................................
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 60 of 60 SUCCESS (0.059 secs / 0.027 secs)
[11:16:46] Finished 'test' after 1.58 s
```

works for mer
